export const books = [
    {
        title: 'Decode and Conquer',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233892/Decode_and_Conquer_lx4bq8.jpg',
        summary: 'Structured product/strategy interview thinking, frameworks, and "sound smart under pressure" tactics.',
        topics: ['Strategy sizing', 'Product sense frameworks', 'Case structuring', 'Metrics talk track', 'Prioritization logic'],
        apmRating: 4,
        tags: ['Interviews', 'Product Strategy', 'Communication'],
        effort: 3,
        business: 3,
        usability: 3,
        readingStatus: 'backlog',
    },
    {
        title: 'Continuous Discovery Habits',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233893/Discovery_Habits_yjdc3b.jpg',
        summary: 'A system for continuous customer learning without "one workshop and we\'re done" delusion.',
        topics: ['Interview cadence', 'Opportunity solution trees', 'Assumption mapping', 'Rapid discovery loops', 'Stakeholder buy-in'],
        apmRating: 5,
        tags: ['Discovery', 'Research', 'PM Craft'],
        effort: 3,
        business: 5,
        usability: 5,
        readingStatus: 'backlog',
    },
    {
        title: 'Losing My Virginity',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233897/losing_virginity_jpqckp.jpg',
        summary: 'Branson\'s high-drama founder storytelling with lessons on brand, risk, and momentum.',
        topics: ['Brand building', 'Storytelling', 'Risk appetite', 'Opportunistic growth', 'PR instincts'],
        apmRating: 3,
        tags: ['Entrepreneurship', 'Branding', 'Leadership'],
        effort: 2,
        business: 2,
        usability: 2,
        readingStatus: 'backlog',
    },
    {
        title: 'Effectuation',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233893/Effectuation_ueojp1.jpg',
        summary: 'Entrepreneurs start with means and constraints, then iterate, instead of pretending they can predict the future.',
        topics: ['Means-driven planning', 'Affordable loss', 'Partnerships', 'Leverage contingencies', 'Uncertainty navigation'],
        apmRating: 4,
        tags: ['Entrepreneurship', 'Strategy', 'Decision-making'],
        effort: 4,
        business: 4,
        usability: 4,
        readingStatus: 'backlog',
    },
    {
        title: '7 Habits of Highly Effective People',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233892/7_Habits_mjk56g.jpg',
        summary: 'A personal operating system: responsibility, priorities, and long-term thinking (annoyingly correct).',
        topics: ['Proactivity', 'Prioritization', 'Goal alignment', 'Relationships', 'Continuous improvement'],
        apmRating: 3,
        tags: ['Productivity', 'Personal Development', 'Leadership'],
        effort: 3,
        business: 2,
        usability: 3,
        readingStatus: 'backlog',
    },
    {
        title: 'Made to Stick',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233898/made_to_stick_o8pghs.jpg',
        summary: 'Why some ideas spread: simplicity + concreteness + emotion + story, not "more slides."',
        topics: ['Message clarity', 'Storytelling', 'Memorability frameworks', 'Persuasion', 'Audience psychology'],
        apmRating: 5,
        tags: ['Communication', 'Marketing', 'Storytelling'],
        effort: 2,
        business: 5,
        usability: 5,
        readingStatus: 'backlog',
    },
    {
        title: 'Good to Great',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233892/71LhjimPd8L._AC_UF1000_1000_QL80__oxbihl.jpg',
        summary: 'Big-company greatness patterns… with shaky causality and a lot of survivorship bias.',
        topics: ['Leadership archetypes', 'Flywheel thinking', 'Discipline culture', 'Focus', 'Organizational momentum'],
        apmRating: 2,
        tags: ['Business', 'Leadership', 'Strategy'],
        effort: 3,
        business: 2,
        usability: 1,
        readingStatus: 'backlog',
    },
    {
        title: 'Marketing for Financial Advisors',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233898/marketing_for_financial_advisors_lgcdvl.jpg',
        summary: 'Trust-heavy marketing: credibility, compliance-aware messaging, authority building.',
        topics: ['Trust signals', 'Positioning', 'Compliance constraints', 'Content strategy', 'Relationship marketing'],
        apmRating: 3,
        tags: ['Marketing', 'Positioning', 'Trust'],
        effort: 2,
        business: 3,
        usability: 3,
        readingStatus: 'backlog',
    },
    {
        title: 'The Courage to Be Disliked',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233905/the_courage_to_be_disliked_uqhk1w.jpg',
        summary: 'Adlerian psychology: stop outsourcing your self-worth, choose your life stance intentionally.',
        topics: ['Personal responsibility', 'Interpersonal boundaries', 'Purpose', 'Emotional independence', 'Life narratives'],
        apmRating: 2,
        tags: ['Psychology', 'Personal Development'],
        effort: 3,
        business: 1,
        usability: 2,
        readingStatus: 'backlog',
    },
    {
        title: 'Experimentation Works',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233893/Experimentation_rzrozv.jpg',
        summary: 'A practical argument: stop trusting vibes, run experiments like adults.',
        topics: ['Experiment culture', 'Hypothesis discipline', 'Org adoption', 'Measurement thinking', 'Iteration loops'],
        apmRating: 5,
        tags: ['Experimentation', 'Analytics', 'Growth'],
        effort: 3,
        business: 5,
        usability: 5,
        readingStatus: 'backlog',
    },
    {
        title: 'Trustworthy Online Controlled Experiments',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233910/trustworthyonlinecontrolledexperiments_ewip30.jpg',
        summary: 'The gnarly reality of A/B testing at scale: bias, logging, stats pitfalls, and infra constraints.',
        topics: ['Experiment design', 'Statistical validity', 'Instrumentation', 'Network effects', 'Guardrails'],
        apmRating: 4,
        tags: ['Experimentation', 'Analytics', 'Data'],
        effort: 5,
        business: 4,
        usability: 4,
        readingStatus: 'backlog',
    },
    {
        title: 'Presentation Secrets of Steve Jobs',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233902/secrets_of_steve_Jobs_dpml9q.jpg',
        summary: 'High-emotion narrative presentation craft (use responsibly, please).',
        topics: ['Story structure', 'Demos', 'Simplicity', 'Rehearsal', 'Audience emotion'],
        apmRating: 3,
        tags: ['Communication', 'Presentations', 'Storytelling'],
        effort: 2,
        business: 3,
        usability: 3,
        readingStatus: 'backlog',
    },
    {
        title: 'Start With Why',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233903/Start_with_why_zgonah.jpg',
        summary: 'Purpose-driven narrative framing; helpful, but over-quoted by people who can\'t execute.',
        topics: ['Purpose statements', 'Leadership narrative', 'Motivation framing', 'Brand story', 'Alignment'],
        apmRating: 3,
        tags: ['Leadership', 'Branding', 'Communication'],
        effort: 2,
        business: 3,
        usability: 2,
        readingStatus: 'backlog',
    },
    {
        title: 'Resonate',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233902/resonate_sgjv1r.jpg',
        summary: 'A blueprint for turning decks into transformation stories (audience as the hero).',
        topics: ['Story arc', 'Contrast ("what is" vs "what could be")', 'Audience journey', 'Narrative beats', 'Persuasion'],
        apmRating: 5,
        tags: ['Communication', 'Presentations', 'Storytelling'],
        effort: 3,
        business: 5,
        usability: 5,
        readingStatus: 'backlog',
    },
    {
        title: 'The Making of a Manager',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233908/the_making_of_a_manger_htgwhy.jpg',
        summary: 'Practical first-time management: 1:1s, feedback, trust, and not being a menace.',
        topics: ['Coaching', 'Feedback', 'Team health', 'Delegation', 'Managing yourself'],
        apmRating: 4,
        tags: ['Management', 'Leadership', 'Teamwork'],
        effort: 2,
        business: 3,
        usability: 4,
        readingStatus: 'backlog',
    },
    {
        title: 'Thinking in Bets',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233909/Thinking_in_Bets_ukrvfq.jpg',
        summary: 'Decision quality ≠ outcome quality; learn to think probabilistically.',
        topics: ['Probabilistic thinking', 'Decision hygiene', 'Outcome bias', 'Uncertainty', 'Learning loops'],
        apmRating: 5,
        tags: ['Decision-making', 'Analytics', 'PM Craft'],
        effort: 3,
        business: 5,
        usability: 5,
        readingStatus: 'backlog',
    },
    {
        title: 'Cracking the PM Interview',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233892/cracking_the_PM_interview_by6xpo.jpg',
        summary: 'Exam prep for PM interviews; useful, but not real-world PMing.',
        topics: ['Product sense questions', 'Metrics questions', 'Execution questions', 'Behavioral prep', 'Frameworks'],
        apmRating: 4,
        tags: ['Interviews', 'PM Craft'],
        effort: 3,
        business: 2,
        usability: 2,
        readingStatus: 'backlog',
    },
    {
        title: 'The Design of Everyday Things',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233905/The_Design_of_everyday_things_m1vkpv.jpg',
        summary: 'Fundamental usability: affordances, feedback, mental models. Permanently changes how you see products.',
        topics: ['Human error', 'Interface design', 'Discoverability', 'Constraints', 'Mental models'],
        apmRating: 5,
        tags: ['Design', 'UX', 'Product Thinking'],
        effort: 3,
        business: 4,
        usability: 5,
        readingStatus: 'backlog',
    },
    {
        title: 'Change by Design',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233893/Change_By_Design_voox02.jpg',
        summary: 'Design thinking as a mindset; inspiring but often vague in execution details.',
        topics: ['Ideation culture', 'Problem framing', 'Prototyping mindset', 'Empathy', 'Innovation narrative'],
        apmRating: 3,
        tags: ['Design', 'Innovation'],
        effort: 2,
        business: 3,
        usability: 2,
        readingStatus: 'backlog',
    },
    {
        title: 'The Four Steps to Epiphany',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233906/The_Four_Steps_to_the_epiphany_a2iewg.jpg',
        summary: 'Customer development before scaling. Stop building blindly.',
        topics: ['Customer discovery', 'Validation', 'Pivoting', 'Go-to-market learning', 'Startup discipline'],
        apmRating: 4,
        tags: ['Startups', 'Discovery', 'Go-to-Market'],
        effort: 4,
        business: 4,
        usability: 4,
        readingStatus: 'backlog',
    },
    {
        title: 'What Customers Want',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233910/what_customers_want_n9pkms.jpg',
        summary: 'Early Jobs-to-be-Done framing: customers hire products for progress.',
        topics: ['Outcome thinking', 'Customer motivation', 'Problem framing', 'Switching behavior', 'Progress narratives'],
        apmRating: 4,
        tags: ['JTBD', 'Product Strategy', 'Marketing'],
        effort: 3,
        business: 4,
        usability: 4,
        readingStatus: 'backlog',
    },
    {
        title: 'Jobs to Be Done',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233896/JTBD_vmq6td.jpg',
        summary: 'More actionable JTBD: structure research and positioning around outcomes and constraints.',
        topics: ['Job statements', 'Forces of progress', 'Segmentation by job', 'Messaging clarity', 'Competitive alternatives'],
        apmRating: 5,
        tags: ['JTBD', 'Marketing', 'Discovery'],
        effort: 3,
        business: 5,
        usability: 5,
        readingStatus: 'backlog',
    },
    {
        title: 'Peak',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233900/Peak_lrc709.jpg',
        summary: 'Skill is built via deliberate practice, not vibes or "talent."',
        topics: ['Deliberate practice', 'Feedback loops', 'Skill decomposition', 'Coaching', 'Performance improvement'],
        apmRating: 3,
        tags: ['Personal Development', 'Learning'],
        effort: 3,
        business: 2,
        usability: 3,
        readingStatus: 'backlog',
    },
    {
        title: 'Radical Focus',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233901/Radical_Focus_pp3qsd.jpg',
        summary: 'OKRs stripped of corporate theater. Focus beats ambition.',
        topics: ['OKR setting', 'Prioritization', 'Focus discipline', 'Alignment', 'Execution cadence'],
        apmRating: 4,
        tags: ['OKRs', 'Execution', 'Strategy'],
        effort: 2,
        business: 4,
        usability: 4,
        readingStatus: 'backlog',
    },
    {
        title: 'Sprint',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233903/Sprint_eze6tt.jpg',
        summary: 'A one-week process to decide + prototype + test. Works only if leadership actually commits.',
        topics: ['Rapid prototyping', 'Structured decision-making', 'User testing', 'Cross-functional alignment', 'Time-boxing'],
        apmRating: 4,
        tags: ['Execution', 'Product Process', 'Discovery'],
        effort: 3,
        business: 4,
        usability: 3,
        readingStatus: 'backlog',
    },
    {
        title: 'HBR Guide to Persuasive Presentations',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233894/HBR_l8xmh3.jpg',
        summary: 'Corporate-safe persuasion mechanics: structure, audience logic, credibility.',
        topics: ['Argument structure', 'Stakeholder persuasion', 'Clarity', 'Executive communication', 'Slide discipline'],
        apmRating: 4,
        tags: ['Communication', 'Presentations', 'Stakeholders'],
        effort: 2,
        business: 4,
        usability: 4,
        readingStatus: 'backlog',
    },
    {
        title: 'Nudge',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233899/Nudge_a0seav.jpg',
        summary: 'Behavioral economics meets choice architecture. Ethically powerful, easily weaponized.',
        topics: ['Defaults', 'Framing effects', 'Incentives', 'Behavioral bias', 'Ethical design'],
        apmRating: 4,
        tags: ['Behavioral Econ', 'Marketing', 'Design'],
        effort: 3,
        business: 4,
        usability: 4,
        readingStatus: 'backlog',
    },
    {
        title: 'Measure What Matters',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233899/Measure_What_Matters_rxz7ss.jpg',
        summary: 'OKRs as alignment tools, not surveillance. Many orgs misuse it anyway.',
        topics: ['OKR frameworks', 'Alignment', 'Goal setting', 'Outcomes vs output', 'Cadence'],
        apmRating: 4,
        tags: ['OKRs', 'Execution', 'Leadership'],
        effort: 2,
        business: 4,
        usability: 4,
        readingStatus: 'backlog',
    },
    {
        title: 'The Hard Thing About Hard Things',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233894/Hard_things_ef8t1q.jpg',
        summary: 'CEO reality: pain, ambiguity, and brutal tradeoffs. Less "inspiration," more "survival."',
        topics: ['Hiring/firing', 'Crisis decisions', 'Culture under pressure', 'Leadership psychology', 'Execution in chaos'],
        apmRating: 3,
        tags: ['Leadership', 'Startups', 'Management'],
        effort: 3,
        business: 3,
        usability: 2,
        readingStatus: 'backlog',
    },
    {
        title: 'Thinking, Fast and Slow',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233909/Thinking_Fast_Slow_jkosvr.jpg',
        summary: 'The canonical book on cognitive biases and dual-system thinking; dense but foundational.',
        topics: ['Biases', 'Heuristics', 'Judgment errors', 'Decision-making', 'Behavioral economics'],
        apmRating: 4,
        tags: ['Psychology', 'Decision-making', 'Behavioral Econ'],
        effort: 5,
        business: 4,
        usability: 3,
        readingStatus: 'in_progress',
    },
    {
        title: 'Swipe to Unlock',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233905/Swipe_to_unlock_wesdnh.jpg',
        summary: 'Friendly overview of how tech products, business models, and platforms work.',
        topics: ['Platform economics', 'Product fundamentals', 'Business models', 'User behavior', 'Tech literacy'],
        apmRating: 4,
        tags: ['Product Basics', 'Tech Literacy'],
        effort: 1,
        business: 3,
        usability: 3,
        readingStatus: 'done',
    },
    {
        title: 'Case Interview Secrets',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233892/case_interview_kkkpgt.jpg',
        summary: 'Case interview playbook: structure, math, hypotheses, and confidence.',
        topics: ['Case structuring', 'Quantitative reasoning', 'Hypothesis-driven analysis', 'Communication', 'Interview performance'],
        apmRating: 3,
        tags: ['Interviews', 'Strategy'],
        effort: 2,
        business: 2,
        usability: 2,
        readingStatus: 'done',
    },
    {
        title: 'The Lean Startup',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233907/The_Lean_Startup_cjilsf.jpg',
        summary: 'Build-measure-learn loops, MVP thinking, and validated learning. Widely cited, unevenly practiced.',
        topics: ['MVPs', 'Iteration loops', 'Innovation accounting', 'Pivot/persevere', 'Hypothesis testing'],
        apmRating: 4,
        tags: ['Startups', 'Experimentation', 'Execution'],
        effort: 2,
        business: 4,
        usability: 4,
        readingStatus: 'done',
    },
    {
        title: 'Leading with Questions',
        coverImage: 'https://res.cloudinary.com/dgglltv04/image/upload/v1771233897/Leading_with_Questions_c6ppw2.jpg',
        summary: 'Leadership via inquiry: better questions produce better thinking and better teams.',
        topics: ['Coaching questions', 'Problem framing', 'Decision facilitation', 'Listening', 'Team development'],
        apmRating: 3,
        tags: ['Leadership', 'Management', 'Communication'],
        effort: 2,
        business: 3,
        usability: 3,
        readingStatus: 'done',
    },
];

// All unique tags for the filter UI
export const allTags = [
    'Analytics', 'Behavioral Econ', 'Branding', 'Business', 'Communication',
    'Data', 'Decision-making', 'Design', 'Discovery', 'Entrepreneurship',
    'Execution', 'Experimentation', 'Go-to-Market', 'Growth', 'Innovation',
    'Interviews', 'JTBD', 'Leadership', 'Learning', 'Management',
    'Marketing', 'OKRs', 'PM Craft', 'Personal Development', 'Positioning',
    'Presentations', 'Product Basics', 'Product Process', 'Product Strategy',
    'Product Thinking', 'Productivity', 'Psychology', 'Research',
    'Stakeholders', 'Startups', 'Storytelling', 'Strategy', 'Teamwork',
    'Tech Literacy', 'Trust', 'UX',
];
